### ISSUE TITLE
Unable to select windows

### ISSUE THREAD

**Issue by julekgwa** [passingthru67/workspaces-to-dock#130]
### Linux Distribution version
Fedora 27 with NVIDIA GTX 1050 graphics card.

### Gnome Shell version
`GNOME Shell 3.26.2`

### Xorg or Wayland (or both)
Wayland

### Extension version or branch
17

### Description of the problem
Unable to select windows after activating `workspace to dock`, I can click on the window but it doesn't become active, and the super key doesn't work also.

### Steps to reproduce the problem
Install the extension in machine that uses NVIDIA GTX 1050 graphics card.

**Comment by passingthru67** [comment]
I need more detail please. I'm not sure what is meant by 'unable to select windows'. Is the whole desktop locked up?

**Comment by truongan** [comment]
This maybe beating a dead horse but I can confirm this problem recently. More details on issue #138

**Comment by julekgwa** [comment]
@passingthru67 I'll test now.

**Comment by julekgwa** [comment]
@passingthru67 It doesn't fix the issue.
![screenshot](https://user-images.githubusercontent.com/5516477/39915287-d294cee2-5507-11e8-8546-4ee84c1f3ae1.png)

**Comment by passingthru67** [comment]
@julekgwa, I still don't have a whole lot to go on. I'm assuming your issue is also in the activities overview (like issue #138)? Do you have a dual monitor setup? If so, I'd like to see what your gnome shell log looks like at the moment things stopped working. Would you run the following command from a terminal ..

journalctl --since "YYYY-MM-DD HH:MM:SS" /usr/bin/gnome-shell > journaldebug.txt

Replace YYYY-MM-DD HH:MM:SS with the date and time (in the appropriate format like 2018-05-10 12:30:00) right before the lock up. Then post the results (journaldebug.txt) or send it to me via email (passingthru67@gmail.com).

**Comment by julekgwa** [comment]
@passingthru67 I think it is related, after installing this extension my laptop behaves as if I have pressed the windows/host key.

**Comment by julekgwa** [comment]
Here's the list of my installed extensions.

![exten](https://user-images.githubusercontent.com/5516477/39920199-8da80830-5516-11e8-8628-1a1576b41909.png)

**Comment by julekgwa** [comment]
Looks like the problem occurs when I have dash to dock extension enabled.

**Comment by passingthru67** [comment]
I believe this issue is the same as #138 and is fixed by the latest commit in the master branch.

Please download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail.com extension folder that contains the extension code. Simply copy that folder to your extensions folder at /home/ME/.local/share/gnome-shell/extensions (replace ME with your actual username). Next, restart Gnome Shell (alt+f2+r) or logout and log back in (if using Wayland). If Workspaces-to-Dock doesn't show up, you may need to enable the extension using Gnome Tweak tool.

**Comment by curvatura99** [comment]
I'm already using the current branch, which I loaded onto my machine last night. Also updated to Gnome 3.28.2 from the proposed Ubuntu repos.

**Comment by passingthru67** [comment]
My mistake. I'll take a look at your logs and see if I notice anything.

**Comment by passingthru67** [comment]
@curvatura99 would you disable your other extensions, restart gnome shell, and then test again. I'm wondering if there is an extension conflict.

**Comment by curvatura99** [comment]
With all of the extensions turned off the application windows appear to be functioning properly. However the "JS ERROR: Error: No signal connection undefined found" fault still occurs in the journal logs.

**Comment by passingthru67** [comment]
I'll check Ubuntu 18.04 tomorrow and see if I get the same errors. In the mean time, try turning on your other extensions (one at a time) and see which one is conflicting with WtD.

**Comment by curvatura99** [comment]
I found the extension that was the problem. It was the no blanking of the lock screen, which was outdated and deprecated. Everything appears to be functional once I removed it.

**Comment by passingthru67** [comment]
@curvatura99 After removing the blanking extension, are you still getting the "JS ERROR: Error: No signal connection undefined found" faults in your journal logs?

**Comment by curvatura99** [comment]
@passingthru67 The "JS ERROR" is gone in the logs. Thank you for your time in resolving this. I appreciate everything your team does.
