### ISSUE TITLE
Moving program window to another workspace hides the Workspace Dock, even with hiding disabled.

### ISSUE THREAD

**Issue by jessedubord** [passingthru67/workspaces-to-dock#92]
###Linux Distribution version
Ubuntu GNOME 17.04 x64

###Gnome Shell version
3.24.0

###Extension version or branch
39

###Description of the problem
Workspace dock retracts/auto-hides/recedes when I click+drag a window on my desktop (in Overview mode) to another workspace.

###Steps to reproduce the problem
1. Open any window (say, Nautilus file browser)
2. Press the SUPER key or Activities button to enter GNOME Activities Overview
3. Click + drag the window you opened to another workspace

###Result
Intermittently, the Workspace Dock will hide itself/disappear/retract to the right edge of the screen. Only by closing and re-opening the Activities Overview can I bring back the Workspace Dock.

###Expected result
No hiding when I click + drag a window to another workspace.

Additional details:
Using Nvidia 375.39 proprietary Nvidia drivers, though this is confirmed on other machines running open-source display drivers, too.
Linux kernel 4.10.0-20-generic

**Comment by passingthru67** [comment]
Is intelligent hiding turned off in the preferences so that the dock is fixed and always visible?

**Comment by jessedubord** [comment]
Yes, the intelligent hiding switch is turned off in the Workspaces to dock preferences.

**Comment by passingthru67** [comment]
The latest commits in the master branch should fix this issue. Since you're using Gnome 3.24, download the master branch zip (https://github.com/passingthru67/workspaces-to-dock/archive/master.zip) and extract it into a temporary folder. Inside of the extracted folder you will find the workspaces-to-dock@passingthru67.gmail folder. Simply copy it to your ~/.local/share/gnome-shell/extensions folder. Next, restart Gnome Shell (alt+f2+r). This way you get the latest enhancements and bug fixes.

**Comment by jessedubord** [comment]
Thanks for the reply and the user-friendly resolution procedures. I downloaded the master zip, extracted and copied into the gnome-shell extensions folder, then restarted the gnome shell. However, the problem persisted, albeit intermittently. For example, moving a Terminal window from the Activities Overview to Workspace 2 with no other windows open won't cause it to auto-hide, but moving the Terminal to Workspace 2 WITH other windows open on it will still trigger the auto-hide bug. I can provide more specific examples if that would be helpful.

**Comment by passingthru67** [comment]
Let me see if I can duplicate the issue first. If I can't, I'll need you to send me your workspaces-to-dock configuration and any other extensions you may have installed.

**Comment by jessedubord** [comment]
Sounds good. Also a side-effect that I noticed from using the master zip you provided: Click+dragging windows around the desktop is VERY laggy, not smooth motions. Disabling the extension fixes this. The windows seem to move around just fine in the Overview.

**Comment by passingthru67** [comment]
Fixed the lag issue with the latest commit. As for your main issue, I'm still not able to duplicate it. Would you provide me with your settings by opening a terminal and typing "dconf dump /org/gnome/shell/extensions/workspaces-to-dock/". Then, copy/paste the results here.

**Comment by passingthru67** [comment]
BTW, are you running on Xorg or Wayland?

**Comment by jessedubord** [comment]
Sure thing, here is the details from dconf:
[/]
autohide=false
intellihide=false
customize-height=true
customize-height-option=1

And I'm running it in Xorg (version 7.7, I believe)

I'm take a video screenshot of the issue. Will upload soon with link.

Other specs:
Two monitors, 1 via hdmi, another via Displayport

**Comment by passingthru67** [comment]
Now I'm seeing what you're describing. But, a video screencast would verify it.

**Comment by jessedubord** [comment]
Here's a video screencast: https://youtu.be/o5BlXv4fj2E (might still be processing on YouTube)

**Comment by jessedubord** [comment]
The auto-hide also seems to happen when moving a program/window from one monitor over into another.

**Comment by passingthru67** [comment]
Download the fix-intellihide branch (https://github.com/passingthru67/workspaces-to-dock/archive/fix-intellihide.zip) and install it as per previous instructions. Let me know if it fixes the issues.

**Comment by jessedubord** [comment]
Just tested on a separate (one-monitor) PC with a GTX 1080 Nvidia card & 375.39 graphics driver. Works perfectly!!! I'll confirm tomorrow morning that it works on the two-monitor PC set-up with the GTX 980ti card. Nice work!!!

**Comment by jessedubord** [comment]
Confirmed this branch fixes the issue on my dual-monitor set-up as well. Awesome! Thanks for your attention and fixing this bug, @passingthru67! Cheers.
